### ISSUE TITLE
Why does wait() throw?

### ISSUE THREAD

**Issue by schwa** [JensRavens/Interstellar#19]
Why does wait throw an error or return a value instead of returning a result? This makes it very hard to use wait while continuing to process signals.

**Comment by JensRavens** [comment]
`wait()` was supposed to be the end of a chain of async transforms - kind of a bridging between Interstellar and the usual Swift error handling, just as `flatMap` also takes a throwing function to get into the Interstellar world. Do you see any use case for waiting and then continuing to process something?

**Comment by schwa** [comment]
I think an example of usage would come in very handy. I understand how it works now but it took me a while to get it.
