### ISSUE TITLE
Adding Signal update(f: T? -> T)

### ISSUE THREAD

**Issue by elm4ward** [JensRavens/Interstellar#22]
First of all - i am loving the simplicity of interstellar! 
ty for putting it online.

In my projects i added an extension for Signals.
I often use this in case of 1 Signal with a Tuple of values.

Maybe you see some use case for this. 

``` swift
extension Signal {
  func update(f: T? -> T){
    // internally:  self.update(f(self.value?.value))
    self.update(f(self.peek()))
  }
}
```

**Comment by JensRavens** [comment]
Can you give me an example how you're using this function? I'm not sure what's the use case actually.

**Comment by elm4ward** [comment]
sure.
e.g.: when there is a signal containing a tuple, it provides me a possibility to update the value while
having access to the previous value. 

``` swift

var tupleSignal: Signal<(String, String)> = Signal("a", "b")

func updateFirst(string: String){
    tupleSignal.update {
      (string, $0!.1)
    }
}
```

**Comment by JensRavens** [comment]
Wouldn't it be easier to just merge two signals in that case?

``` swift
let a = Signal("a")
let b = Signal("b")
let tupleSignal = a.merge(b)

a.update("some new value") // tupleSignal now contains ("some new value", "b")
```

**Comment by elm4ward** [comment]
in case I need to be able to observe both on their own? sure. 
but this way it is possible to save those extra signals. 
so there is only 1 instead of 3. 
e.g. I am using it for sort and filter of data sources, where I can easily forget about the individual signals. 
no worries if you don't see the use case. I can easily live on w/ an extension. 
:-)

**Comment by JensRavens** [comment]
The problem with your implementation is, that it will crash if one of the values becomes an error. 

Handling tuples/merging signals is still not completely thought through, so I'm open to suggestions (see #16).
