### ISSUE TITLE
Yosemite support

### ISSUE THREAD

**Issue by danielrhammond** [JensRavens/Interstellar#30]
Hey, I was curious on what the intended/expected minimum OS X target is. 

The README says the requirements are `iOS 7.0+ / Mac OS X 10.9+ / Ubuntu 14.10` but when I use Carthage fetch and install Interstellar it results in a framework with minimum deployment target of `OS X 10.11`

I tried to change the `Interstellar.xcodeproj` to set a deployment target of 10.10, it builds fine... but I'm wondering whether its just an issue with the `.xcodeproj` and it should work fine or if the documentation is out of date. Any guidance would be helpful, thanks.

**Comment by JensRavens** [comment]
The only requirement for Interstellar is swift support (done in os x 10.9). This seems to be an error in the OS X target. To be honest, I don't use Carthage, so I didn't notice so far. I'll try to fix this asap.

**Comment by danielrhammond** [comment]
Awesome, thanks a lot for the very-quick response. 

I was originally going to just throw up a pull with the original question changing the xcode project file but I couldn't seem to figure out how to run the tests against the OS X framework (works when I select the iOS scheme in Xcode/xcodebuild but not OS X) any advice/pointers on how to do that?

**Comment by JensRavens** [comment]
Currently there are no OS X tests at all (os x code is 100% identical to iOS, therefore there are only iOS tests).

**Comment by danielrhammond** [comment]
Cool, thanks for explanation. Thought I was missing something.

**Comment by JensRavens** [comment]
Deployment targets should be correct now in V2.
