### ISSUE TITLE
More complex unsubscription in v2

### ISSUE THREAD

**Issue by ashfurrow** [JensRavens/Interstellar#40]
The current subscription/unsubscription mechanism in v2 relies on having both the `Observable` and the `ObserverToken`, which complicates things slightly. For use in a table view cell, for example, we need to unsubscribe during `prepareForReuse()`, and afterward set the observable and the token to be `nil`. This requires some awkwardness, either with:

``` swift
if let observerToken = observerToken, observable = observable {
    observable.unsubscribe(observerToken)
}
self.observerToken = nil
self.observable = nil
```

Or something with tuples:

``` swift
var subscription: (ObserverToken, Observable<Whatever>)?

...

if let subscription = subscription {
    subscription.1.unsubscrive(subscription.0)
}
subscription = nil
```

Neither is particularly awesome. I'd like to consider using a more complex `ObserverToken` that has a weak or unowned reference to the observable it's bound to, so we don't need to hang on to both observable and observer token. Any thoughts? Happy to send a PR if you like the idea.

**Comment by ashfurrow** [comment]
Hey there! Any update on this? Is it an idea you think is worth pursuing?

**Comment by JensRavens** [comment]
That sounds like a good idea.

But here's another solution for your problem:

``` swift
class CellHolder {
  weak cell: UITableViewCell
  func doStuffOnCell(value: T) {}
}

class Cell: UITableViewCell {
  var holder: CellHolder?

  func setupCell(observable) {
    observable.subscribe {[weak holder] t: T in
      holder?.doStuffOnCell(t)
    }
  }

  override func prepareForReuse() {
    holder = nil
  }
}
```

This saves you from the hassle of constantly subscribing/unsubscribing during `prepareForReuse` and let ARC handle the task for you. 

Only drawback: After the cell is `dealloc`ed the subscription stays around. I haven't done any performance testing on that yet but I assume it's more performant on the long term.

**Comment by ashfurrow** [comment]
Yeah, that's makes sense. In our case, we're going to have a few hundred observables each subscribed to hundreds and hundreds of times, in an app that needs to be remain usable during hours of use (edge case, but it's important). Usually I've followed this example, but in a few instances, I need to unsubscribe from popular observables. 

I'll send a PR with a sample implementation, I'd love to get your feedback.

**Comment by JensRavens** [comment]
Thank you! (I'm a quite busy until next Wednesday, so responses might take a bit)

**Comment by JensRavens** [comment]
Unsubscribe has now landed in V2, therefore closing this issue.
