### ISSUE TITLE
Not sure about how `debounce` works

### ISSUE THREAD

**Issue by vittoriom** [JensRavens/Interstellar#44]
Hi!

I'm using `Interstellar` in our project and so far it's working fine.
There is a use case where I can update a signal multiple times in a short period but I'm only interested in one update every let's say half a second. It's fine to discard the previous updates, I'm just interested in the latest one.
I'm using `debounce` for this, but looking at the tests (and at the wrong outcome in the app), calling `next`  on a debounced signal will still fire the callback as many times as updates on the original signal.
Is this the intended behavior and how can I discard previous updates?

The main goal I'm trying to achieve is to have some kind of buffer (a `[Int]`) that can be filled and flushed every half a second at most

Thanks!

**Comment by JensRavens** [comment]
If debounce is still calling your subscriber for each update, something is wrong 😀

In the test it's actually testing that some values should be discarded. It pretty much works like this:
- First update is supplied immediately (if there are less frequent updates this is desired behaviour)
- next update is delayed up to the interval that is specified as an argument
- if there is another update during this timespan, the last value is discarded and the new value takes it's place (this does **not** reset the timer though to have consistent update calls)

Basic use case would be a textfield sending a signal on each key press, but only querying the network / database once per second. I used this in a few apps so far and it did work as intended. If it's not working for you like this it would be great to see a code snipped from you to reproduce this error.

**Comment by vittoriom** [comment]
Ha, I see! I wasn't actually getting a call for each update, but I was assuming that by just looking at the tests. Maybe they could be modified so that `update` is called 3 times and yet 2 callbacks are fired. I think this would make the behavior more clear.

Anyway, thanks for the explanation. I think the part I missed (and didn't expect) was the first update that is fired immediately. 

I'll close this since now the logic is clarified. Thanks!
