### ISSUE TITLE
Swift 3 version

### ISSUE THREAD

**Issue by AmitaiB** [JensRavens/Interstellar#50]
...would be awesome. 

I'm using a modified fork of 
    https://github.com/madhavajay/Interstellar/tree/swift-3
 at the moment, but it would be grand to have something official.

And thank you for your awesome framework!  🙏

**Comment by JensRavens** [comment]
Thanks for your work. Please see `feature/v2` for Swift 3 support and lots of awesome new stuff. I hope to release all of this this week.

**Comment by asalom** [comment]
Do you have any plans to release the Swift 3 version soon?
Thanks for the good work!
