### ISSUE TITLE
Question regarding Thread class

### ISSUE THREAD

**Issue by anaglik** [JensRavens/Interstellar#53]
During migration to Interstellar 2 I noticed that `Thread` class is not "supported" both in `Signal` and `Observable`. I tried to used it as suggested in description (`Signal.ensure(Thread.main)`) but ensure method expects something else. Do you plan to remove it completely or there is some other method that I didn't noticed.

**Comment by JensRavens** [comment]
`Thread` has been replaced by `Queue` in v2, mostly because it never has been a thread but a queue instead, but also because `Interstellar.Thread` in Swift 3 clashes with `Foundation.Thread` wich has been renamed from `NSThread`.

**Comment by anaglik** [comment]
It totally makes sense. Nonetheless, `ensure` method works neither with `Thread` nor `Queue` class. It is not big deal since Signal is deprecated and you will probably remove both Thread and Queue classes in future. 
Thank's for help.
