### ISSUE TITLE
global(qos:) only available on OSX 10.10

### ISSUE THREAD

**Issue by robertoschwald** [JensRavens/Interstellar#54]
While trying to compile feature/v2 with Xcode 8.1, OSX 10.12 in Carthage, I get:

Carthage/Checkouts/Interstellar/Sources/Threading.swift:47:23: error: 'global(qos:)' is only available on OS X 10.10 or newer

Carthage/Checkouts/Interstellar/Sources/Threading.swift:47:36: error: 'background' is only available on OS X 10.10 or newer

A shell task failed with exit code 65:
*\* BUILD FAILED **

The following build commands failed:
    CompileSwift normal x86_64
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by JensRavens** [comment]
Thank you for reporting, the issue was fixed in #51.
