### ISSUE TITLE
Using Queue with observable, maybe race condition?

### ISSUE THREAD

**Issue by nicholaslythall** [JensRavens/Interstellar#60]
I'm trying to use `Queue.background` and `Queue.main` to do some background work on another thread and then publish the result on the main thread. Based on the signatures of the `Queue` functions and my experience with 1.0 I'm assuming I'm supposed to use it something like this:

```swift
func longRunningTask(arg: String) -> Observable<Result<[String]>> {
    // takes a few seconds to complete, 
    return Observable(.success(["foo", "bar"])
}

func fetchArray(arg: String) -> Observable<Result<[String]>> {
    return Observable<String>(arg)
    .flatMap(Queue.background)
    .flatMap(longRunningTask)
    .flatMap(Queue.main)
}

@IBAction onClick(_ sender: Any) {
   activityIndicator.startAnimating()
   fetchArray("exampleValue")
   .next {
        activityIndicator.stopAnimating()
    }
}
```

Is the basically how I should be using the Queue functions?

If it is, I've found that roughly 50% of the time, `activityIndicator.stopAnimating()` won't be called on the main thread, but instead will be called from the background thread.

I think this is caused by the Observable created by the block created by `Queue.queue<T>(_ queue: DispatchQueue)` having it's update method called on the new thread before anything is subscribed to it. Then when the original thread gets around to calling subscribe the observable immediately executes the subscribe block because of the saved value update the was dispatched on the other thread.

**Comment by JensRavens** [comment]
Yes, this is currently a known issue about first subscription. Subscribing to an observable that already holds a value will execute the subscription immediately on the subscriber thread, all subsequent updates will respect the invocation chain. 

If you just care about stopping the indicator I'd suggest you use an observable with `.NoInitialValue` which does not keep the value around and therefore skips this problem.
